version: '3.5'

services:
  db:
    container_name: database
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./pg-init.sql:/docker-entrypoint-initdb.d/master_db_init.sql"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  pgdata: