server:
  address: 0.0.0.0
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}?currentSchema=app
      username: ${POSTGRES_USER:dbuser}
      password: ${POSTGRES_PASSWORD:pass}
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
